CheffFoodBlog/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace CheffFoodBlog.Models
{
    public class Recipe
    {
        [Key]
        public int RecipeID { get; set; }

        public string Name { get; set; }

        public int CheffID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        public DateTime DateCreation { get; set; }

        public string CreationProcess { get; set; }

        public virtual Cheff Cheff { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
    }

    public class GroupByCheffModel
    {
        public int CheffID { get; set; }

        public string CheffFirstName { get; set; }

        public string CheffLasttName { get; set; }

        public int TotalRecipes { get; set; }
    }
}

CheffFoodBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CheffFoodBlog.Models;

namespace CheffFoodBlog.Controllers
{
    public class CommentsController : Controller
    {
        private readonly CheffFoodBlogContext _context;

        public CommentsController(CheffFoodBlogContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var cheffFoodBlogContext = _context.Comment.Include(c => c.Recipe);
            return View(await cheffFoodBlogContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.Recipe)
                .FirstOrDefaultAsync(m => m.CommentID == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["RecipeID"] = new SelectList(_context.Recipe, "RecipeID", "RecipeID");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentID,RecipeID,Title,AuthorName,Content")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipeID"] = new SelectList(_context.Recipe, "RecipeID", "RecipeID", comment.RecipeID);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["RecipeID"] = new SelectList(_context.Recipe, "RecipeID", "RecipeID", comment.RecipeID);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CommentID,RecipeID,Title,AuthorName,Content")] Comment comment)
        {
            if (id != comment.CommentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RecipeID"] = new SelectList(_context.Recipe, "RecipeID", "RecipeID", comment.RecipeID);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comment
                .Include(c => c.Recipe)
                .FirstOrDefaultAsync(m => m.CommentID == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comment.FindAsync(id);
            _context.Comment.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
            return _context.Comment.Any(e => e.CommentID == id);
        }
    }
}

CheffFoodBlog/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CheffFoodBlog.Models;

namespace CheffFoodBlog.Controllers
{
    public class RecipesController : Controller
    {
        private readonly CheffFoodBlogContext _context;

        public RecipesController(CheffFoodBlogContext context)
        {
            _context = context;
        }

        // GET: Recipes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Recipe.ToListAsync());
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .FirstOrDefaultAsync(m => m.RecipeID == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RecipeID,Name,CheffID,DateCreation,CreationProcess")] Recipe recipe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RecipeID,Name,CheffID,DateCreation,CreationProcess")] Recipe recipe)
        {
            if (id != recipe.RecipeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.RecipeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipe
                .FirstOrDefaultAsync(m => m.RecipeID == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipe = await _context.Recipe.FindAsync(id);
            _context.Recipe.Remove(recipe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
            return _context.Recipe.Any(e => e.RecipeID == id);
        }

        //https://localhost:44313/Recipes/Filter?RecipeName=yaniv

        public ActionResult Filter(string RecipeName, string CheffFirstName, string ChefflastName)
        {
            var results = _context.Recipe.AsQueryable();

            //_context.Recipe.AsQueryable();
            //var results;

            // recipe query by cheff last name and first name
            if (!string.IsNullOrEmpty(CheffFirstName) && !string.IsNullOrEmpty(ChefflastName))
            {
                // query join between cheffs and recipes
                results = from recipe in _context.Recipe
                          join cheff in _context.Cheff
                          on recipe.CheffID equals cheff.ID
                          where cheff.LastName == ChefflastName  && cheff.FirstName == CheffFirstName
                          select recipe;//,Name,CheffID,FirstName,LastName;
            }

            // recipe query by either last name or either first name
            if (!string.IsNullOrEmpty(CheffFirstName) || !string.IsNullOrEmpty(ChefflastName))
            {
                // query join between cheffs and recipes
                results = from recipe in _context.Recipe
                          join cheff in _context.Cheff
                          on recipe.CheffID equals cheff.ID
                          where cheff.LastName == ChefflastName || cheff.FirstName == CheffFirstName
                          select recipe;//,Name,CheffID,FirstName,LastName;
            }

            // if we want to filter by recipe Name
            if (!string.IsNullOrEmpty(RecipeName))
            {
                results = results.Where(currRecipe => currRecipe.Name == RecipeName);
            }   


            //return View("Index",results);
            return View("Index", results);
        }

        public ActionResult GroupByCheff()
        {
            var totalRecipes = from recipe in _context.Recipe
                               group recipe by recipe.CheffID into Group
                               join cheff in _context.Cheff on Group.Key equals cheff.ID
                               select new GroupByCheffModel()
                               {
                                   CheffFirstName = cheff.FirstName,
                                   CheffLasttName = cheff.LastName,
                                   CheffID = cheff.ID,
                                   TotalRecipes = Group.Sum(p => 1)
                               };

            return View(totalRecipes.ToList());
        }


    }
}

CheffFoodBlog/Views/Recipes/Create.cshtml
@model CheffFoodBlog.Models.Recipe

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cheff.FirstName + " " + model.Cheff.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cheff.FirstName + " " + model.Cheff.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cheff.FirstName + " " + model.Cheff.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="display-in-row">
                <label>Cheff</label>
                @Html.DropDownList("CheffID",
                    new SelectList((IEnumerable<CheffFoodBlog.Models.Cheff>)ViewData["cheffsSelectable"], "ID", "FirstName"), new { @class = "btn btn-default" })


                @Html.ValidationMessageFor(model => model.Cheff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationProcess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationProcess, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationProcess, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CheffFoodBlog/Views/Recipes/Delete.cshtml
@model CheffFoodBlog.Models.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cheff.FirstName + " " + model.Cheff.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cheff.FirstName + " " + model.Cheff.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cheff)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cheff)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationProcess)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationProcess)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CheffFoodBlog/Views/Recipes/Details.cshtml
@model DisneyPrincessesBlog.Models.Post
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ready(function () {
        var token = $('[name=__RequestVerificationToken]').val();
		var bodyData = {
			cheffId: "@Model.Cheff.ID",
            currentRecipeId: "@Model.RecipeID"
        };
        bodyData['__RequestVerificationToken'] = token;
        $.ajax({
            url: "/Recipes/WantMore",
            type: "Recipe",
            data: bodyData,
            success: function (response) {
                var el = document.getElementById("moreRecipes");

                if (!response.error) {
                    el.href = response.url;
                }
                else {
                    el.parentElement.removeChild(el);
                }
            },
            error: function (res) {
                console.log('err', res)
            }
        });

    });
</script>

@{
    ViewBag.Title = "Details";
}

<div class="blog-post">
    <p class="blog-post-title">@Html.DisplayFor(model => model.Name) </p>

    <div class="blog-post-meta">@Html.DisplayFor(model => model.DateCreation)</div>
    <p>@Html.DisplayFor(model => model.CreationProcess)</p>

    <a id="morePosts">Want more posts of @Html.DisplayFor(model => model.Cheff.FirstName)? click here</a>
    <footer class="blockquote-footer">@Html.DisplayFor(model => model.Cheff.FirstName), <cite>@Html.DisplayFor(model => model.Cheff.FirstName)</cite></footer>
</div>

<div class="container">
    <h3>Comments:</h3>
    <br />
    <ul class="comments-list col-md-8" id="comment-list">@Html.DisplayFor(model => model.Comments)</ul>
</div>
<div class="add-comment">
    @Html.Action("Add", "Comments", new { RecipeID = Model.RecipeID });


</div>
<hr>
<div class="container">    
    @Html.ActionLink("Back to List", "Index")
</div>

CheffFoodBlog/Views/Recipes/Edit.cshtml
@model CheffFoodBlog.Models.Recipe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Recipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecipeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cheff.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cheff.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cheff.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cheff, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CheffID",
                    new SelectList((IEnumerable<CheffFoodBlog.Models.Cheff>)ViewData["cheffesSelectable"], "ID", "FirstName"), new { @class = "btn btn-default" })

                @Html.ValidationMessageFor(model => model.Cheff, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationProcess, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationProcess, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationProcess, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CheffFoodBlog/Views/Recipes/GroupByRecipes.cshtml
@model IEnumerable<CheffFoodBlog.Models.GroupByCheffModel>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/d3")
<head>
    <style>
        .axis {
            font: 10px sans-serif;
        }

        .bar {
            fill: steelblue;
        }

            .bar:hover {
                fill: brown;
            }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
    </style>
</head>
<script type="text/javascript">
    $(document).ready(function () {
        var svg = d3.select("svg"),
            margin = { top: 20, right: 20, bottom: 30, left: 40 },
            width = +svg.attr("width") - margin.left - margin.right,
            height = +svg.attr("height") - margin.top - margin.bottom;

        var x = d3.scaleBand().rangeRound([0, width]).padding(0.1),
            y = d3.scaleLinear().rangeRound([height, 0]);

        var g = svg.append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        d3.json("/Posts/GroupByCheffData", function (data) {
            x.domain(data.map(function (d) { return d.CheffFirstName; }));
            y.domain([0, d3.max(data, function (d) { return d.TotalRecipes; })]);

            g.append("g")
                .attr("class", "axis axis--x")
                .attr("transform", "translate(0," + height + ")")
                .call(d3.axisBottom(x));

            g.append("g")
                .attr("class", "axis axis--y")
                .call(d3.axisLeft(y).ticks(d3.max(data, function (d) { return d.TotalRecipes; })))
                .append("text")
                .attr("transform", "rotate(-90)")
                .attr("y", 6)
                .attr("dy", "0.71em")
                .attr("text-anchor", "end")
                .text("Frequency");

            g.selectAll(".bar")
                .data(data)
                .enter().append("rect")
                .attr("class", "bar")
                .attr("x", function (d) { return x(d.CheffFirstName); })
                .attr("y", function (d) { return y(d.TotalRecipes); })
                .attr("width", x.bandwidth())
                .attr("height", function (d) { return height - y(d.TotalRecipes); });

        })

    })
</script>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CheffFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalRecipes)
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CheffFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalRecipes)
            </td>
        </tr>
    }
</table>
<br />
<u><b>Statistics:</b></u>
<br />
<svg width="480" height="250"></svg>

CheffFoodBlog/Views/Recipes/Index.cshtml
@model IEnumerable<CheffFoodBlog.Models.Recipe>

<div id="multicolumns" class="mul-col-blue container text-center">

    <section id="videoContainer">
        <!-- Introduction -->
        <video width="400" controls>
            <source src="~/Media/videos/10SecretFactsAboutDISNEYPrincesses.mp4" type="video/mp4">
        </video>
    </section>
    <canvas id="myCanvas" width="300" height="100"></canvas>
</div>

<script>
    const size = 500;
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.font = "30px Arial";
    ctx.strokeText("Recipes", 20, 40);
</script>


<div class="container">
    @{
        Dictionary<string, int> counterDictionary = (Dictionary<string, int>)Session["counterDictionary"];
        if (counterDictionary != null)
        {
            string favCheffName = counterDictionary.FirstOrDefault(x => x.Value == counterDictionary.Values.Max()).Key;
            <div class="alert alert-success">Like @Html.Raw(favCheffName)? @Html.ActionLink("click", "Filter", new { CheffName = favCheffName }) for more</div>
        }
    }

    @using (Html.BeginForm("Filter", "Posts", FormMethod.Post, new { @class = "form-inline" }))
    {
        <h3>Filter posts by</h3>
        /* TODO
        <div class="form-group">
            @Html.DropDownList("princessRoyaltyType", EnumHelper.GetSelectList(typeof(DisneyPrincessesBlog.Models.KingdomType)), "RoyaltyType", new { @class = "form-control" })
        </div>
        */
    
        <div class="form-group">
            @Html.TextBox("CheffName", "", new { @class = "form-control", placeholder = "Cheff Name" })
        </div>

        <input class="btn btn-search-posts" type="submit" value="Search" />
    }



    <hr />
    <div class="container row">
        <div class="list-inline buttons">
            @using (Html.BeginForm("GroupByCheff", "Recipes"))
            {
                <input class="btn btn-lg btn-stats" type="submit" value="Posts Stats" />
                <p class="btn btn-lg btn-add-blog" href="#" role="button">@Html.ActionLink("Add Recipe", "Create", null, new { @style = "color: #FF8A80;" })</p>
            }

        </div>
    </div>


</div>


<hr />


@foreach (var item in Model)
{
    <div class="blog-post">
        <p class="blog-post-title">@Html.ActionLink(item.Name, "Details", new { id = item.RecipeID }, new { @style = "text-decoration:none; color: black;" }) </p>

        <div class="blog-post-meta">@Convert.ToString(string.Format("{0:dd/MM/yyyy}", item.DateCreation))</div>
        <p>@Html.DisplayFor(modelItem => item.CreationProcess)</p>

        <footer class="blockquote-footer">@Html.DisplayFor(modelItem => item.Cheff.FirstName + " " + item.Cheff.LastName) </footer>
        @{ if (Request.IsAuthenticated)
            {
                <div>
                    @Html.ActionLink("Edit", "Edit", new { id = item.RecipeID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.RecipeID })
                </div>
            }
        }
    </div>
}